from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('dashboard/', views.user_dashboard, name="dashboard"),
    path('dashboard-admin-ticket/', views.admin_dashboard_ticket, name="dashboard-admin-ticket"),
    path('dashboard-admin-ticket/admin-dashbord-ticket-ajax/', views.admin_dashbord_ticket_ajax, name="ajax-dashbord-ticket-ajax"),
    path('dashboard-admin-commercial/', views.admin_dashboard_commercial, name="dashboard-admin-commercial"),
    path('dashboard-admin-commercial/admin-dashbord-commercial-ajax/', views.admin_dashbord_commercial_ajax, name="ajax-dashbord-commercial-ajax"),
    path('dashboard-admin-bis/', views.dashboard_for_admin),
    path('dashboard-admin-commercial/admin-dashbord-commercial-ajax/', views.admin_dashbord_commercial_ajax, name="ajax-dashbord-analytique-ajax"),
    path('dashboard-admin-analytique/', views.admin_dashboard_analytique, name="dashboard-admin-analytique"),
    path('dashboard-admin-analytique/admin-dashbord-analytique-ajax/', views.admin_dashboard_analytique_ajax, name="ajax-dashbord-analytique-ajax"),
    path('profil/', views.user_profile, name="profil"),
    path('delete_notif/<int:id_notif>/', views.delete_notif, name="delete_notif"),
    path('demandes/', views.user_demandes, name="demandes"),
    path('download-doc/<str:name>/', views.download_doc),
    path('consulting-docs/', views.consulting_docs),
    path('contrats-certificats/', views.contrats_et_certificats, name="contrats-certificats"),
    path('factures/', views.factures, name="factures"),
    path('check-invoice/', views.check_invoice),
    path('consulting-choice/', views.consulting_choice, name="consulting-choice"),
    path('consulting/', views.demande_consulting, name="consulting"),
    path('upload-choice/', views.upload_choice, name="upload-choice"),
    path('upload/', views.upload_docs, name="upload"),
    path('validate-docs/<int:id_demande>/', views.validate_docs, name="validate-docs"),
    path('documents/', views.doc_consulting, name="documents"),
    path('documents/<int:id_doc>/', views.delete_docs, name="delete"),
    path('demande/<int:id_demande>/', views.delete_demande, name="delete-demande"),
    path('return-loc/<str:id_demande>/', views.return_loc, name="return-loc"),
    path('new-demande-loc-super-admin/', views.new_demande_loc, name="new-demande-loc-super-admin"),
    path('new-demande-loc/', views.new_demande_loc, name="new-demande-loc"),
    path('new-demande-bail/', views.new_demande_bail, name="new-demande-bail"),
    path('new-demande-bail-super-admin/', views.new_demande_bail, name="new-demande-bail-super-admin"),
    path('new-demande-garantie/', views.new_demande_garantie, name="new-demande-garantie"),
    path('new-demande-garantie-super-admin/', views.new_demande_garantie, name="new-demande-garantie-super-admin"),
    path('new-demande-eligibilite/', views.new_demande_eligibilite, name="new-demande-eligibilite"),
    path('new-demande-eligibilite-super-admin/', views.new_demande_eligibilite, name="new-demande-eligibilite-super-admin"),
    path('new-demande-complete/', views.new_demande_complete, name="new-demande-complete"),
    path('new-demande-complete-super-admin/<str:type>/', views.new_demande_complete_super_admin, name="new-demande-complete-super-admin"),
    path('retour-after-complete-super-admin/<str:type>/',views.retour_after_complete_super_admin, name="retour-after-complete-super-admin"),

    path('delete-demande/<int:id_demande>', views.delete_demande),
    path('update-choice/', views.update_choice, name="update-choice"),
    path('update-demande-loc/', views.update_demande_loc, name="update-demande-loc"),
    path('update-demande-loc-admin/', views.update_demande_loc, name="update-demande-loc-admin"),
    path('update-demande-bail/', views.update_demande_bail, name="update-demande-bail"),
    path('update-demande-bail-admin/', views.update_demande_bail, name="update-demande-bail-admin"),
    path('update-demande-garantie/', views.update_demande_garantie, name="update-demande-garantie"),
    path('update-demande-garantie-admin/', views.update_demande_garantie, name="update-demande-garantie-admin"),
    path('update-demande-eligibilite/', views.update_demande_eligibilite, name="update-demande-eligibilite"),
    path('update-demande-eligibilite-admin/', views.update_demande_eligibilite, name="update-demande-eligibilite-admin"),
    path('update-demande-complete/', views.update_demande_complete, name="update-demande-complete"),
    path('tickets-consulting/', views.tickets_consulting, name="tickets-consulting"),
    path('new-ticket/', views.new_ticket, name="new-ticket"),

    path('admin-select/<int:id_demande>/',views.admin_select,name="admin-select"),
    
    # remplacer les underscore par des tiret du 6
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="admin/password_reset.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="admin/password_reset_sent.html"), name="password_reset_done"),
    path('reset_password/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="admin/password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="admin/password_reset_done.html"), name="password_reset_complete"),

    path('get_password/', views.PasswordResetView_extend.as_view(template_name="admin/new-demande-complete-super-admin.html"), name="get_password"),
    path('get_password_update/',views.PasswordResetView_extend_update.as_view(template_name="admin/update-demande-complete-super-admin.html"), name="get_password_update"),
    path('reset_password_sent_extend/', views.PasswordResetDoneView_extend.as_view(template_name="admin/password_reset_sent.html"), name="password_reset_done_extend"),
    
    path('get_new_admin/', views.PasswordResetView_createAdmin.as_view(template_name="admin/new-admin.html"), name="get_new_admin"),


    path('crm-customers-admin/',views.crm_customers_admin, name="customers-admin"),
    path('crm-leads-admin/change/',views.leads_changement_etats),
    path('crm-leads-admin/',views.crm_leads_admin, name="leads-admin"),
    path('modify-user-super-admin-choice/',views.modify_user_super_admin_choice,name="modify_user_super_admin_choice"),
    path('modify-user-super-admin/',views.modify_user_super_admin,name="modify_user_super_admin"),
    path('pages-notif-admin/',views.pages_notif_admin,name="pages-notif-admin"),
    path('crm-leads-admin/modify-demande-super-admin/<str:id_demande>/',views.modify_demande_super_admin, name="modify_demande_super_admin"),
    path('pages-notif/',views.pages_notif_admin,name="pages-notif-admin"),
    path('crm-leads-admin/modify-demande-super-admin/<str:id_demande>/',views.modify_demande_super_admin, name="modify_demande_super_admin"),
    path('documents_admin/<int:id_doc>/', views.delete_admin_docs, name="delete_admin"),
    path('crm-leads-admin/documents_admin_All/<int:id_demande>/', views.delete_admin_all_docs, name="delete_admin_allType"),
    path('message-choice/', views.message_choice, name="message-choice"),
    path('message/', views.message, name="message"),
    path('tickets/',views.tickets, name="tickets"),
    path('redirectNotifButton/<str:id_notif>/', views.redirectNotifButton, name="redirectNotifButton"),
    path('crm-contacts-admin/', views.crm_contact_admin, name="crm-contacts-admin"),
    path('crm-contacts-admin/ajax-change-etat-contact/',views.ajax_change_etat_contact, name="ajax-change-etat-contact"),
    path('tickets/ajax-change-etat-tickets/',views.ajax_change_etat_tickets, name="ajax-change-etat-tickets"),
    path('ajax_get-demande-super-admin/',views.ajax_get_demande_super_admin, name="ajax_get_demande_super_admin"),
    path('ajax_get_message/',views.ajax_get_message, name="ajax_get_message"),
    path('demande-en-cours-admin/',views.demande_en_cours_admin, name="demande-en-cours-admin"),

    path('update-demande-loc-admin/ajax_siret/',views.ajax_siret,name='ajax_siret_update'),
    path('new-demande-loc-super-admin/ajax_siret/',views.ajax_siret,name='ajax_siret'),
    path('new-demande-loc/ajax_siret/',views.ajax_siret,name='ajax_siret'),
    
    path('download-doc/<str:name>/', views.download_doc),
    path('docusign-signature/', views.docusign_signature),
    path('get-envelope-status/<envelope_id>/', views.get_envelope_status),

    path('send-payment-link/', views.send_payment_link),

    path('<str:page>/', views.view)
]
